post http://localhost:4000/user/add
Content-Type: application/json

{
    "name": "Aliasd123",
    "email": "ali@gmasdail123.cUm",
    "username": "Ali1231231231",
    "password": "antoinedebes",
    "isAdmin": true,
    "phone": "034971231489",
    "address": "beirasut"
}