PUT http://localhost:4000/user/update/60e43dfbd44fb6503309b1ff
Content-Type: application/json

{
    "name": "Ali123",
    "email": "ali@gmail123.cUm",
    "username": "Ali1231231231",
    "password": "bcrypt.hashSync('1231234', 8)",
    "isAdmin": true,
    "phone": "03497489",
    "address": "beirut"
}